name: Example workflow

on: [push]

jobs:

  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # https://stackoverflow.com/questions/58134793/error-while-loading-shared-libraries-libnss3-so-while-running-gtlab-ci-job-to
      # https://github.com/browser-actions/setup-chrome/issues/240
      - name: Install Chrome deps
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 \
          libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120

      # It is important to install java before installing clojure tools which needs java
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Clojure CLI
        shell: bash
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.11.1.1347.sh && \
          chmod +x linux-install-1.11.1.1347.sh && \
          ./linux-install-1.11.1.1347.sh

      - name: Build the jar
        run: clojure -T:build server-uberjar

      - name: List the results
        shell: bash
        run: |
          ls -al target

      - name: Set up the Chrome Driver
        uses: nanasess/setup-chromedriver@v2

      - name: Set up the Chrome options
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
